class PageInfo:
    title = "//h3[contains(@class, 'FormLayout')]"
    url = 'https://staging.karirlab.co/resume-builder'


class ResumeInfo:
    title = "#resInfoTitle"
    name_label = "#resInfoNameTitle"
    name_input = "#resInfoNameField"
    lang_label = "#resInfoLangTitle"
    lang_input = "[overlayid='resInfoLangLists']"
    lang_id = "#resInfoLangID"
    lang_en = "#resInfoLangEN"
    goal_label = "#resInfoGoalTitle"
    goal_desc = "#resInfoGoalDesc"
    goal_input = "#resInfoGoalField"
    goal_content_empty = "div[overlayid='resInfoGoalLists'] .ant-select-selection-placeholder"
    goal_content_selected = "div[overlayid='resInfoGoalLists'] .ant-select-selection-item"
    goal_lists = "#resInfoGoalLists"
    goal_items = "(//div[contains(@class,'GoalItem')])"
    import_btn = "#resInfoImportBtn"
    import_modal = "//div[contains(@class, 'importDataModal')]"


class DataDiri:
    title = "#selfInfoTitle"
    main_form = "#selfInfoToggle"
    form_state = "#selfInfoToggle .ant-collapse-header"
    main_hint = "#selfInfoHint"
    hint_btn = "#selfInfoHintBtn"
    hint_title = "(//span[@class='ant-typography']//strong)[1]"
    hint_desc = "#selfInfoHintDesc"
    first_name_label = "#selfInfoFirstNameLabel"
    first_name_input = "#selfInfoFirstNameInput"
    last_name_label = "#selfInfoLastNameLabel"
    last_name_input = "#selfInfoLastNameInput"
    email_label = "#selfInfoEmailLabel"
    email_input = "#selfInfoEmailInput"
    phone_label = "#selfInfoPhoneLabel"
    phone_input = "#selfInfoPhoneInput"
    country_label = "#selfInfoCountryLabel"
    country_input = "[name='country']"
    country_content = "div[name='country'] .ant-select-selection-item"
    country_lists = "#selfInfoCountryLists"
    country_wni = "#selfInfoCountryIndo"
    country_wna = "#selfInfoCountryNonIndo"
    province_label = "#selfInfoProvinceLabel"
    province_input = "//div[@name='province']//input"
    province_empty = "//div[@name='province']//span[contains(@class,'placeholder')]"
    province_selected = "//div[@name='province']//span[contains(@class,'item')]"
    province_lists = "(//div[contains(@class,'holder-inner')])[2]"
    province_item = "((//div[contains(@class,'holder-inner')])[2]//div[contains(@class,'item')])"
    city_label = "#selfInfoCityLabel"
    city_input = "#selfInfoCityInput"
    city_empty = "//div[@name='city']//span[contains(@class,'placeholder')]"
    city_selected = "//div[@name='city']//span[contains(@class,'item')]"
    city_lists = "(//div[contains(@class,'holder-inner')])[2]"
    address_label = "#selfInfoAddressLabel"
    address_input = "#selfInfoAddressInput"
    linkedin_label = "#selfInfoLinkedinLabel"
    linkedin_input = "#selfInfoLinkedinInput"
    portfolio_label = "#selfInfoPortfolioLabel"
    portfolio_input = "#selfInfoPortfolioInput"
    submit_btn = "#selfInfoSubmitBtn"


class EduHistory:
    add_btn = "#educationAdd"
    toggle = "#educationToggle"
    title = "#educationTitle"
    hint_btn = "#educationHintBtn"
    hint_desc = "#educationHintDesc"
    degree_label = "#educationDegreeLabel"
    degree_input = "#educationDegreeInput"
    name_label = "#educationNameLabel"
    name_input = "#educationNameInput"
    faculty_label = "#educationFacultyLabel"
    faculty_input = "#educationFacultyInput"
    final_score_label = "#educationFinalScoreLabel"
    final_score_input = "#educationFinalScoreInput"
    max_final_score_label = "#educationMaxFinalScoreLabel"
    max_final_score_input = "#educationMaxFinalScoreInput"
    country_label = "#educationCountryLabel"
    country_input = "#educationCountryInput"
    country_lists = "#educationCountryList"
    province_label = "#educationProvinceLabel"
    province_input = "#educationProvinceInput"
    province_lists = "#educationProvinceList"
    city_label = "#educationCityLabel"
    city_input = "#educationCityInput"
    city_lists = "#educationCityList"
    start_label = "#educationStartLabel"
    start_input = "#educationStartInput"
    end_label = "#educationEndLabel"
    end_input = "#educationEndInput"
    form_save_btn = "#educationFormSave"
    form_cancel_btn = "#educationFormCancel"


class JobHistory:
    hint = "#occupationHint"
    hint_btn = "#occupationHintBtn"
    hint_desc = "#occupationHintDesc"
    position_input = "#occupationPositionInput"
    company_name_label = "#companyNameLabel"
    company_name_input = "#companyNameInput"
    company_country_label = "#companyCountryLabel"
    company_country_select = "#companyCountrySelect"
    company_country_lists = "#companyCountryList"
    company_province_label = "#companyProvinceLabel"
    company_province_input = "#companyProvinceInput"
    company_province_lists = "#companyProvinceList"
    company_city_label = "#companyCityLabel"
    company_city_input = "#companyCityInput"
    company_city_lists = "#companyCityList"
    status_label = "#occupationStatusLabel"
    status_input = "#occupationStatusInput"
    status_lists = "#occupationStatusList"
    start_label = "#occupationStartLabel"
    start_input = "#occupationStartInput"
    end_label = "#occupationEndLabel"
    end_input = "#occupationEndInput"
    form_cancel = "#occupationFormCancel"
    form_save = "#occupationFormSave"


class Proficiency:
    hint_btn = "#proficiencyHintBtn"
    hint_desc = "#proficiencyHintDesc"
    name_label = "#proficiencyNameLabel"
    name_input = "#proficiencyNameInput"
    level_label = "#proficiencyLevelLabel"
    level_input = "#proficiencyLevelInput"
    level_lists = "#proficiencyLevelLists"
    level_item_pemula = "//div[@id='proficiencyLevelItem' and @title='Pemula']"
    level_item_menengah = "//div[@id='proficiencyLevelItem' and @title='Menengah']"
    level_item_lanjut = "//div[@id='proficiencyLevelItem' and @title='Lanjut']"
    form_cancel = "#proficiencyFormCancel"
    form_save = "#proficiencyFormSave"


class Achievements:
    hint_btn = "#achievementHintBtn"
    hint_desc = "#achievementHintDesc"
    year_label = "#achievementYearLabel"
    year_input = "#achievementYearInput"
    name_label = "#achievementNameLabel"
    name_input = "#achievementNameInput"
    form_cancel = "#achievementFormCancel"
    form_save = "#achievementFormSave"


class Hobby:
    hint_btn = "#hobbyHintBtn"
    hint_desc = "#hobbyHintDesc"
    name_label = "#hobbyNameLabel"
    name_input = "#hobbyNameInput"
    form_cancel = "#hobbyFormCancel"
    form_save = "#hobbyFormSave"
