class PageInfo:
    title = "//h3[contains(@class, 'FormLayout')]"
    url = 'https://staging.karirlab.co/resume-builder'


class ResumeInfo:
    title = "#resInfoTitle"
    name_label = "#resInfoNameTitle"
    name_input = "#resInfoNameField"
    lang_label = "#resInfoLangTitle"
    lang_input = "[overlayid='resInfoLangLists']"
    lang_id = "#resInfoLangID"
    lang_en = "#resInfoLangEN"
    goal_label = "#resInfoGoalTitle"
    goal_desc = "#resInfoGoalDesc"
    goal_input = "#resInfoGoalField"
    goal_content_empty = "div[overlayid='resInfoGoalLists'] .ant-select-selection-placeholder"
    goal_content_selected = "div[overlayid='resInfoGoalLists'] .ant-select-selection-item"
    goal_lists = "#resInfoGoalLists"
    goal_items = "(//div[contains(@class,'GoalItem')])"
    import_btn = "#resInfoImportBtn"
    import_modal = "//div[contains(@class, 'importDataModal')]"


class DataDiri:
    title = "#selfInfoTitle"
    main_form = "#selfInfoToggle"
    form_state = "#selfInfoToggle .ant-collapse-header"
    main_hint = "#selfInfoHint"
    hint_btn = "#selfInfoHintBtn"
    hint_title = "div[id='selfInfoHint'] strong"
    hint_desc = "#selfInfoHintDesc"
    wrapper = "//div[contains(@class, 'wrapper-self-info')]"
    first_name_label = "#selfInfoFirstNameLabel"
    first_name_input = "#selfInfoFirstNameInput"
    last_name_label = "#selfInfoLastNameLabel"
    last_name_input = "#selfInfoLastNameInput"
    email_label = "#selfInfoEmailLabel"
    email_input = "#selfInfoEmailInput"
    phone_label = "#selfInfoPhoneLabel"
    phone_input = "#selfInfoPhoneInput"
    country_label = "#selfInfoCountryLabel"
    country_input = "[name='country']"
    country_content = "div[name='country'] .ant-select-selection-item"
    country_lists = "#selfInfoCountryLists"
    country_wni = "#selfInfoCountryIndo"
    country_wna = "#selfInfoCountryNonIndo"
    province_label = "#selfInfoProvinceLabel"
    province_input = "//div[@name='province']//input"
    province_empty = "//div[@name='province']//span[contains(@class,'placeholder')]"
    province_selected = "//div[@name='province']//span[contains(@class,'item')]"
    province_lists = "(//div[contains(@class,'holder-inner')])[2]"
    province_item = "((//div[contains(@class,'holder-inner')])[2]//div[contains(@class,'item')])"
    city_label = "#selfInfoCityLabel"
    city_input = "#selfInfoCityInput"
    city_empty = "//div[@name='city']//span[contains(@class,'placeholder')]"
    city_selected = "//div[@name='city']//span[contains(@class,'item')]"
    city_lists = "(//div[contains(@class,'holder-inner')])[2]"
    address_label = "#selfInfoAddressLabel"
    address_input = "#selfInfoAddressInput"
    linkedin_label = "#selfInfoLinkedinLabel"
    linkedin_input = "#selfInfoLinkedinInput"
    portfolio_label = "#selfInfoPortfolioLabel"
    portfolio_input = "#selfInfoPortfolioInput"
    submit_btn = "#selfInfoSubmitBtn"
    fill_name = "|BELUM|#DataProfInfoSelfDataName"
    fill_email = "|BELUM|#DataProfInfoSelfDataEmail"
    fill_phone = "|BELUM|#DataProfInfoSelfDataPhone"
    fill_province = "|BELUM|#DataProfInfoSelfDataProvince"
    fill_city = "|BELUM|#DataProfInfoSelfDataCity"
    fill_address = "|BELUM|#DataProfInfoSelfDataAddress"
    fill_linkedin = "|BELUM|#DataProfInfoSelfDataLinkedin"
    fill_linkedin_checkbox = "|BELUM|#DataProfInfoSelfDataLinkedin-checkbox-fill"
    fill_portfolio = "|BELUM|#DataProfInfoSelfDataPortfolio"
    fill_portfolio_checkbox = "|BELUM|#DataProfInfoSelfDataPortfolio-checkbox-fill"


class EduHistory:
    add_btn = "#educationAdd"
    toggle = "//div[id='educationToggle'] div[role='button']"
    title = "#educationTitle"
    description = "//div[@id='educationToggle']//span[contains(@class,'secondary')]"
    hint_main = "#educationHint"
    hint_title = "div[id='educationHint'] strong"
    hint_btn = "#educationHintBtn"
    hint_desc = "#educationHintDesc"
    wrapper = "//div[contains(@class, 'wrapper-education')]"
    degree_label = "#educationDegreeLabel"
    degree_input = "[overlayid='educationDegreeList']"
    degree_content = "div[overlayid='educationDegreeList'] .ant-select-selection-item"
    degree_lists = "#educationDegreeList"
    degree_sma = "//div[@id='educationDegreeItem' and contains(@title,'SMA')]"
    degree_d1 = "//div[@id='educationDegreeItem' and contains(@title,'D1')]"
    degree_d2 = "//div[@id='educationDegreeItem' and contains(@title,'D2')]"
    degree_d3 = "//div[@id='educationDegreeItem' and contains(@title,'D3')]"
    degree_d4 = "//div[@id='educationDegreeItem' and contains(@title,'D4')]"
    degree_s1 = "//div[@id='educationDegreeItem' and contains(@title,'S1')]"
    degree_s2 = "//div[@id='educationDegreeItem' and contains(@title,'S2')]"
    degree_s3 = "//div[@id='educationDegreeItem' and contains(@title,'S3')]"
    degree_course = "//div[@id='educationDegreeItem' and contains(@title,'Kursus')]"
    name_label = "#educationNameLabel"
    name_input = "#educationNameInput"
    name_empty = "div[name='education_name'] .ant-select-selection-placeholder"
    name_selected = "div[name='education_name'] .ant-select-selection-item"
    name_list = "//div[@id='educationNameList']//div[contains(@class, 'holder-inner')]"
    name_item = "(//div[@id='educationNameItem'])"
    name_add = "//div[@id='educationNameList']/div[contains(@class, 'addMenu')]"
    faculty_label = "#educationFacultyLabel"
    faculty_input = "#educationFacultyInput"
    faculty_list = "//div[@id='educationFacultyList']//div[contains(@class, 'holder-inner')]"
    faculty_add = "//div[@id='educationFacultyList']/div[contains(@class, 'addMenu')]"
    faculty_item = "//div[@id='educationFacultyList']//div[contains(@class, 'item-option')]"
    faculty_empty = "div[name='education_faculty'] .ant-select-selection-placeholder"
    faculty_selected = "div[name='education_faculty'] .ant-select-selection-item"
    gpa_label = "#educationFinalScoreLabel"
    gpa_input = "#educationFinalScoreInput"
    gpa_increase = "(//span[@role='button' and contains(@class, 'up')])[1]"
    gpa_decrease = "(//span[@role='button' and contains(@class, 'down')])[1]"
    max_gpa_label = "#educationMaxFinalScoreLabel"
    max_gpa_input = "#educationMaxFinalScoreInput"
    max_gpa_increase = "(//span[@role='button' and contains(@class, 'up')])[2]"
    max_gpa_decrease = "(//span[@role='button' and contains(@class, 'down')])[2]"
    country_label = "#educationCountryLabel"
    country_input = "#educationCountryInput"
    country_lists = "#educationCountryList"
    country_content = "div[name='education_country'] .ant-select-selection-item"
    country_wni = "educationCountryIndo"
    country_wna = "educationCountryNonIndo"
    province_label = "#educationProvinceLabel"
    province_input = "#educationProvinceInput"
    province_empty = "//div[@name='education_province']//span[contains(@class,'placeholder')]"
    province_lists = "#educationProvinceList"
    city_label = "#educationCityLabel"
    city_input = "#educationCityInput"
    city_empty = "//div[@name='education_city']//span[contains(@class,'placeholder')]"
    city_lists = "#educationCityList"
    start_label = "#educationStartLabel"
    start_input = "#educationStartInput"
    end_label = "#educationEndLabel"
    end_input = "#educationEndInput"
    end_status = "//div[contains(@class, 'EducationForm')]"
    end_status_check = "//div[contains(@class, 'EducationForm')]//input[@name='is_present']"
    save_btn = "#educationFormSave"
    cancel_btn = "#educationFormCancel"
    fill_education_item = "|BELUM|//div[contains(@class,'education-item')]"
    fill_name = "|BELUM|#dataProfInfoEduName"
    fill_country = "|BELUM|#dataProfInfoEduLocCountry"
    fill_province = "|BELUM|#dataProfInfoEduLocProvince"
    fill_city = "|BELUM|#dataProfInfoEduLocCity"
    fill_degree = "|BELUM|#dataProfInfoEduDetailsDegree"
    fill_faculty = "|BELUM|#dataProfInfoEduDetailsFaculty"
    fill_start = "|BELUM|#dataProfInfoEduDetailsStart"
    fill_end = "|BELUM|#dataProfInfoEduDetailsEnd"
    fill_score_checkbox = "|BELUM|#dataProfInfoEduScoreCheckBox"
    fill_final_score = "|BELUM|#dataProfInfoEduFinalScore"
    fill_max_score = "|BELUM|#dataProfInfoEduMaxScore"
    fill_education_description_item = "//div[contains(@class,'DataProfInfoJobDescItem')]"
    fill_education_description_add = "|BELUM|#educationDescriptionAdd"


class JobHistory:
    add_btn = "#addOccupation"
    toggle = "//div[id='occupationToggle'] div[role='button']"
    title = "#occupationTitle"
    hint = "#occupationHint"
    hint_btn = "#occupationHintBtn"
    hint_desc = "#occupationHintDesc"
    wrapper = "//div[contains(@class, 'wrapper-occupation')]"
    position_label = "|BELUM|#occupationPositionLabel"
    position_input = "#occupationPositionInput"
    company_name_label = "#companyNameLabel"
    company_name_input = "#companyNameInput"
    company_country_label = "#companyCountryLabel"
    company_country_select = "#companyCountrySelect"
    company_country_lists = "#companyCountryList"
    company_province_label = "#companyProvinceLabel"
    company_province_input = "#companyProvinceInput"
    company_province_lists = "#companyProvinceList"
    company_city_label = "#companyCityLabel"
    company_city_input = "#companyCityInput"
    company_city_lists = "#companyCityList"
    status_label = "#occupationStatusLabel"
    status_input = "#occupationStatusInput"
    status_lists = "#occupationStatusList"
    start_label = "#occupationStartLabel"
    start_input = "#occupationStartInput"
    end_label = "#occupationEndLabel"
    end_input = "#occupationEndInput"
    end_status_check = "//div[contains(@class, 'OccupationForm')]//input[@name='is_present']"
    form_cancel = "#occupationFormCancel"
    form_save = "#occupationFormSave"

    occupation_item = "|BELUM|//div[contains(@class,'occupation-item')]"
    fill_title = "|BELUM|#dataProfInfoJobTitle"
    fill_company = "|BELUM|#dataProfInfoJobCompanyName"
    fill_type = "|BELUM|#dataProfInfoJobType"
    fill_country = "|BELUM|#dataProfInfoJobLocCountry"
    fill_province = "|BELUM|#dataProfInfoJobLocProvince"
    fill_city = "|BELUM|#dataProfInfoJobLocCity"
    fill_start = "|BELUM|#dataProfInfoJobDurationStart"
    fill_end = "|BELUM|#dataProfInfoJobDurationEnd"
    fill_occupation_description_item = ""
    fill_occupation_description_add = "|BELUM|#occupationDescriptionAdd"
    fill_occupation_recommendation_add = "|BELUM|#occupationRecommendationAdd"
    recommendation_wrapper = "|BELUM|#recommendationWrapper"
    recommendation_title = "|BELUM|#recommendationTitle"
    recommendation_description = "|BELUM|#recommendationDesc"
    recommendation_create_btn = "|BELUM|#recommendationAddBtn"
    recommendation_quota = "|BELUM|#recommendationQuota"
    recommendation_item = "|BELUM|//div[contains(@class, 'recommendation-item')]"
    recommendation_pagination = "|BELUM|#recommendationPagination"


class Proficiency:
    wrapper = "//div[contains(@class, 'wrapper-proficiency')]"
    add_btn = "#addProficiency"
    title = "#proficiencyTitle"
    toggle = "//div[id='proficiencyToggle'] div[role='button']"
    hint_btn = "#proficiencyHintBtn"
    hint_desc = "#proficiencyHintDesc"
    name_label = "#proficiencyNameLabel"
    name_input = "#proficiencyNameInput"
    level_label = "#proficiencyLevelLabel"
    level_input = "#proficiencyLevelInput"
    level_lists = "#proficiencyLevelLists"
    level_item_pemula = "//div[@id='proficiencyLevelItem' and @title='Pemula']"
    level_item_menengah = "//div[@id='proficiencyLevelItem' and @title='Menengah']"
    level_item_lanjut = "//div[@id='proficiencyLevelItem' and @title='Lanjut']"
    form_cancel = "#proficiencyFormCancel"
    form_save = "#proficiencyFormSave"

    fill_proficiency_item = "|BELUM|#proficiencyItem"
    fill_checkbox = "|BELUM|//div[@id='proficiencyItem']//label[@class='ant-checkbox-wrapper']/span[@class='ant-checkbox']/input[@type='checkbox']"
    fill_name = "|BELUM|#dataProfInfoSkillName"
    fill_level = "|BELUM|#dataProfInfoSkillLevel"

class Achievements:
    wrapper = "//div[contains(@class, 'wrapper-achievement')]"
    add_btn = "#addAchievement"
    title = "#achievementTitle"
    toggle = "//div[id='achievementToggle'] div[role='button']"
    hint_btn = "#achievementHintBtn"
    hint_desc = "#achievementHintDesc"
    year_label = "#achievementYearLabel"
    year_input = "#achievementYearInput"
    name_label = "#achievementNameLabel"
    name_input = "#achievementNameInput"
    form_cancel = "#achievementFormCancel"
    form_save = "#achievementFormSave"

    fill_achievement_item = "|BELUM|#achievementItem"
    fill_checkbox = "|BELUM|//div[@id='achievementItem']//label[@class='ant-checkbox-wrapper']/span[@class='ant-checkbox']/input[@type='checkbox']"
    fill_name = "|BELUM|#dataProfInfoAwardName"
    fill_level = "|BELUM|#dataProfInfoAwardYear"

class Hobby:
    wrapper = "//div[contains(@class, 'wrapper-hobby')]"
    add_btn = "#addInterest"
    title = "#hobbiesTitle"
    toggle = "//div[id='hobbiesToggle'] div[role='button']"
    hint_btn = "#hobbyHintBtn"
    hint_desc = "#hobbyHintDesc"
    name_label = "#hobbyNameLabel"
    name_input = "#hobbyNameInput"
    form_cancel = "#hobbyFormCancel"
    form_save = "#hobbyFormSave"

    fill_hobby_item = "|BELUM|#hobbyItem"
    fill_checkbox = "|BELUM|//div[@id='hobbyItem']//label[@class='ant-checkbox-wrapper']/span[@class='ant-checkbox']/input[@type='checkbox']"
    fill_name = "|BELUM|#hobbyName"

class Score: 
    score_progress = "//div[contains(@class, 'previewLayout__score')]//div[contains(@class, 'ant-progress-inner')]"
    score_text = "//div[contains(@class, 'previewLayout__score')]//div[contains(@class, 'ant-progress-inner')]//span[contains(@class, 'ant-progress-text')]"
    score_title = "//div[contains(@class, 'previewLayout__scoreDetail')]//span[contains(@class, 'ant-typography')]//strong"
    score_rank = "#resumeStatusTag"
    score_description = "#scoreDescription"

class Styling:
    template_action = "#templateOptions"
    template_popup = "//div[contains(@class, 'previewLayout__templateOptions__radioGroup')]"
    template_options = "//div[contains(@class, 'previewLayout__templateOptions__radioGroup')]//label[contains(@class,'ant-radio-wrapper-in-form-item')]"
    font_action = "#fontOptions"
    font_arial = "#fontOption_arial"
    font_montserrat = "#fontOption_montserrat"
    font_roboto = "#fontOption_roboto"
    font_times = "#fontOption_times_new_roman"
    color_action = "#colorOptions"
    color_purple = "#colorOption_PURPLE"
    color_lightBlue = "#colorOption_LIGHT_BLUE"
    color_darkBlue = "#colorOption_DARK_BLUE"
    color_black = "#colorOption_BLACK"
    fullscreen_action = "#fullscreenIcon"

class Preview:
    name = "|BELUM|#previewResumeName"
    phone = "|BELUM|#previewResumePhone"
    email = "|BELUM|#previewResumeEmail"
    address = "|BELUM|#previewResumeAddress"
    city = "|BELUM|#previewResumeCity"
    province = "|BELUM|#previewResumeProvince"
    website = "|BELUM|#previewResumeWebsite"
    linkedin = "|BELUM|#previewResumeLinkedIn"
    education_section = "|BELUM|#previewEducationSection"
    education_title = "|BELUM|#previewEducationSectionTitle"
    education_items = "|BELUM|//div[contains(@class, 'previewEducationItems')]"
    education_items_name = "|BELUM|//div[contains(@class, 'previewEducationItems')]//span[@id='previewEducationItemsName']"
    education_items_degree = "|BELUM|//div[contains(@class, 'previewEducationItems')]//span[@id='previewEducationItemsDegree']"
    education_items_faculty = "|BELUM|//div[contains(@class, 'previewEducationItems')]//span[@id='previewEducationItemsFaculty']"
    education_items_gpa = "|BELUM|//div[contains(@class, 'previewEducationItems')]//span[@id='previewEducationItemsGPA']"
    education_items_province = "|BELUM|//div[contains(@class, 'previewEducationItems')]//span[@id='previewEducationItemsProvince']"
    education_items_city = "|BELUM|//div[contains(@class, 'previewEducationItems')]//span[@id='previewEducationItemsCity']"
    education_items_start = "|BELUM|//div[contains(@class, 'previewEducationItems')]//span[@id='previewEducationItemsStart']"
    education_items_end = "|BELUM|//div[contains(@class, 'previewEducationItems')]//span[@id='previewEducationItemsEnd']"
    education_items_achievements = "|BELUM|//div[contains(@class, 'previewEducationItems')]//span[contains(@class, educationItemsAchievements)]"
    occupation_section = "|BELUM|#previewOccupationSection"
    occupation_title = "|BELUM|#previewOccupationSectionTitle"
    occupation_items = "|BELUM|//div[contains(@class, 'previewOccupationItems')]"
    occupation_items_company = "|BELUM|//div[contains(@class, 'previewOccupationItems')]//span[@id='previewOccupationItemsCompany']"
    occupation_items_position = "|BELUM|//div[contains(@class, 'previewOccupationItems')]//span[@id='previewOccupationItemsPosition']"
    occupation_items_type = "|BELUM|//div[contains(@class, 'previewOccupationItems')]//span[@id='previewOccupationItemsType']"
    occupation_items_province = "|BELUM|//div[contains(@class, 'previewOccupationItems')]//span[@id='previewOccupationItemsProvince']"
    occupation_items_city = "|BELUM|//div[contains(@class, 'previewOccupationItems')]//span[@id='previewOccupationItemsCity']"
    occupation_items_start = "|BELUM|//div[contains(@class, 'previewOccupationItems')]//span[@id='previewOccupationItemsStart']"
    occupation_items_end = "|BELUM|//div[contains(@class, 'previewOccupationItems')]//span[@id='previewOccupationItemsEnd']"
    occupation_items_achievements = "|BELUM|//div[contains(@class, 'previewOccupationItems')]//span[contains(@class, 'previewOccupationItemsAchievements')]"
    additionalInfo_section = "|BELUM|#previewAdditionalInfoSection"
    additionalInfo_title = "|BELUM|#previewAdditionalInfoSectionTitle"
    skill_title = "|BELUM|#previewSkillTitle"
    skill_items = "|BELUM|//span[contains(@class, 'previewSkillItems')]"
    skill_items_name = "|BELUM|//span[contains(@class, 'previewSkillItems')]//span[contains(@class, 'previewSkillItemsName')]"
    skill_items_level = "|BELUM|//span[contains(@class, 'previewSkillItems')]//span[contains(@class, 'previewSkillItemsLevel')]"
    achievement_title = "|BELUM|#previewAchievementTitle"
    achievement_items = "|BELUM|//span[contains(@class, 'previewAchievementItems')]"
    achievement_items_name = "|BELUM|//span[contains(@class, 'previewAchievementItems')]//span[contains(@class, 'previewAchievementItemsName')]"
    achievements_items_year = "|BELUM|//span[contains(@class, 'previewAchievementItems')]//span[contains(@class, 'previewAchievementItemsYear')]"
    hobby_title = "|BELUM|#previewHobbyTitle"
    hobby_items = "|BELUM|#previewHobbyItems" "//span[contains(@class, 'previewHobbyItems')]"

class Action:
    preview_title = "#previewLayoutTitle"
    save = "#previewLayoutSaveResume"