*** Variables ***
#ELEMENT ADMIN LOGIN
${ADMIN_TEXT_EMAIL}    //*[@id="__next"]/div/div[2]/div/div/form/div[1]/div/div[1]/label
${ADMIN_TEXT_PASSWORD}    //*[@id="__next"]/div/div[2]/div/div/form/div[2]/div/div[1]/label
${ADMIN_FIELD_EMAIL}    //*[@id="username"]
${ADMIN_FIELD_PASSWORD}    //*[@id="password"]
${ADMIN_BUTTON_LOGIN}    xpath://*[@id="__next"]/div/div[2]/div/div/form/div[4]/div/div/div/div/button