name: Playwright Pipeline Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3]
        shardTotal: [3]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    - name: Install Allure CLI
      run: |
        ALLURE_VERSION=2.21.0
        curl -Ls "https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz" -o allure.tgz
        tar -zxvf allure.tgz
        sudo mv allure-${ALLURE_VERSION} /opt/allure
        export PATH=$PATH:/opt/allure/bin
      shell: bash

    - name: Run tests with reporter
      run: |
        pytest --env=test --mode=pipeline --headless --alluredir=allure-results -n=auto --screenshot=only-on-failure --video=retain-on-failure

    - name: Upload results to Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-${{ matrix.shardIndex }}
        path: allure-results
        retention-days: 10

  generate-report:
    if: always()
    needs: [run-tests]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Download Allure results from artifacts
      uses: actions/download-artifact@v4
      with:
        name: 'allure-results-*'
        path: merged-allure-results
        merge-multiple: true

    - name: Generate Allure Report
      run: |
        /opt/allure/bin/allure generate merged-allure-results --clean -o allure-report

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages
