name: Playwright Pipeline Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3]
        shardTotal: [3]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest allure-pytest playwright
        pip install -r requirements.txt

    - name: Install browsers
      run: playwright install

    - name: Install Allure CLI
      run: pip install allure-cli==2.13.2

    - name: Run tests
      run: |
        pytest --env=test --mode=pipeline --headless --alluredir=allure-results-${{ matrix.shardIndex }} -n=auto --screenshot=only-on-failure --video=retain-on-failure

    - name: Upload results to Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-${{ matrix.shardIndex }}
        path: allure-results-${{ matrix.shardIndex }}
        retention-days: 10

  generate_and_deploy:
    needs: test_and_deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Allure results
      uses: actions/download-artifact@v4
      with:
        name: allure-results-*
        path: merged-allure-results

    - name: Generate Allure Report
      run: allure generate merged-allure-results --clean -o allure-report

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages
