name: Pipeline Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [ karirlab-FE-trigger ]

permissions:
  contents: write
  pages: write

jobs:
  test-execution:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Runner
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install --with-deps
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Test execution
      run: |
        pytest --env=test --mode=pipeline --headless --alluredir=allure-results -n=auto --reruns=2 --reruns-delay=4 --screenshot=only-on-failure --video=retain-on-failure

    - name: Publishing the report
      run: |
        git clone --branch=gh_pages --single-branch https://github.com/${{ github.repository }} gh_pages || true
        simple-elf/allure-report-action@v1.7 --gh_pages gh_pages --allure_history allure-history --allure_results allure-results
        peaceiris/actions-gh-pages@v3 --github_token ${{ secrets.GITHUB_TOKEN }} --publish_branch gh_pages --publish_dir allure-history

