name: KarirLab Robot Framework Tests

on:
  push:
    branches: [ main ] # Need to change to BE main/ FE Main
  pull_request:
    branches: [ main ] # Need to change to BE main/ FE Main

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: 3.9

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-browser
        rfbrowser init

    - name: Run Robot Framework tests
      run: |
        robot tests/
      continue-on-error: true

    - name: Archive Robot Framework results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: robotframework-results
        path: output/
